# Generated by Django 5.2.1 on 2025-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='نام استان')),
                ('city', models.CharField(default='', max_length=100, verbose_name='نام شهر')),
                ('neighborhood_type', models.CharField(default='', max_length=100, verbose_name='گونه محله')),
                ('title', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مساحت عرصه (متر مربع)')),
                ('land_use', models.CharField(default='', max_length=100, verbose_name='نوع کاربری')),
                ('residential_units', models.IntegerField(default=0, verbose_name='تعداد واحد مسکونی')),
                ('commercial_units', models.IntegerField(default=0, verbose_name='تعداد واحد تجاری')),
                ('service_units', models.IntegerField(default=0, verbose_name='تعداد واحد خدماتی')),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='برآورد حدودی حجم سرمایه\u200cگذاری (میلیون ریال)')),
            ],
        ),
    ]
