# Generated by Django 5.2.1 on 2025-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='بخش')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='موقعیت مکانی')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='میزان سرمایه\u200cگذاری (میلیون یورو)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
    ]
