# Generated by Django 5.2.1 on 2025-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='location',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='sector',
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مساحت عرصه (متر مربع)'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='نام شهر'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='commercial_units',
            field=models.IntegerField(default=0, verbose_name='تعداد واحد تجاری'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='land_use',
            field=models.CharField(default='', max_length=100, verbose_name='نوع کاربری'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='neighborhood_type',
            field=models.CharField(default='', max_length=100, verbose_name='گونه محله'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='نام استان'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='residential_units',
            field=models.IntegerField(default=0, verbose_name='تعداد واحد مسکونی'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='service_units',
            field=models.IntegerField(default=0, verbose_name='تعداد واحد خدماتی'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='برآورد حدودی حجم سرمایه\u200cگذاری (میلیون ریال)'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='نام پروژه'),
        ),
    ]
